# This workflow will build the Docker image from the Dockerfile and push it to Docker Hub

name: Build and Push Docker Image

on:
  push:
    branches:
    - "master"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PW: ${{ secrets.DOCKER_PW }}

    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    # Log in to Docker Hub using credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      run: |
        echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin

    # Build Docker image from Dockerfile
    - name: Build Docker image
      run: |
        docker build -t zekath/mynginx:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push zekath/mynginx:latest
