# This workflow will build the GithubActionsDemo project and push a Docker image

name: GithubActionsDemo

on:
  push:
    branches:
    - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Adjust version as needed

    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Restore dependencies (install NuGet packages)
      run: dotnet restore "GithubActionsDemo.csproj"

    - name: Build and publish the app
      run: |
        dotnet build "GithubActionsDemo.csproj" --no-restore
        dotnet publish "GithubActionsDemo.csproj" -c Release -o ./publish

    - name: Upload app artifacts to Github
      uses: actions/upload-artifact@v4
      with:
        name: app-artifacts
        path: ./publish

  # Docker build and push job
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t zekath/mydotnetapp:latest .

    - name: Push Docker image
      run: docker push zekath/mydotnetapp:latest

  deploy:
    runs-on: self-hosted
    needs: docker

    steps:
    - name: Download the artifacts from Github (from the build job)
      uses: actions/download-artifact@v4
      with:
        name: app-artifacts

    - name: Stop the application service
      run: |
        sudo systemctl stop GithubActionsDemo.service        

    - name: Deploy the application
      run: |
        sudo rm -Rf /opt/GithubActionsDemo || true
        sudo cp -r /home/azureuser/actions-runner/_work/GithubActionsDemo/GithubActionsDemo/ /opt/GithubActionsDemo        

    - name: Start the application service
      run: |
        sudo systemctl start GithubActionsDemo.service
