# This workflow creates a Dockerfile, builds the Docker image, and pushes it to Docker Hub

name: Build and Push Docker Image

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      working-directory: path
      run: docker build . -t docker-hub-zekath/mydotnetapp:latest


    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PW }}
      run: |
        echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Push the images to Docker Hub
      run: docker push docker-hub-zekath/mydotnetapp:latest

    - name: Push Docker image to Docker Hub
      run: docker push zekath/mydotnetapp:latest
