# This workflow will build a Docker image and push it to Docker Hub

name: Build and Push Docker Image

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v4

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies (install Nuget packages)
      run: dotnet restore

    - name: Build and publish the app
      run: |
        dotnet build --no-restore
        dotnet publish -c Release -o ./publish

    - name: Create Dockerfile
      run: |
        cat <<EOF > Dockerfile
        # Use the .NET SDK to build the project
        FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
        WORKDIR /src
        COPY . .
        RUN dotnet restore "GithubActionsDemo.csproj"
        RUN dotnet build "GithubActionsDemo.csproj" -c Release --no-restore
        RUN dotnet publish "GithubActionsDemo.csproj" -c Release -o /app/publish
        
        # Use the ASP.NET runtime to run the app
        FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
        WORKDIR /app
        COPY --from=build /app/publish .
        ENTRYPOINT ["dotnet", "GithubActionsDemo.dll"]
        EOF

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t zekath/mydotnetapp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push zekath/mydotnetapp:latest
