# This workflow creates a Dockerfile, builds the Docker image, and pushes it to Docker Hub

name: Build and Push Docker Image

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Create a Dockerfile
      run: |
        cat <<EOF > Dockerfile
        # Use the .NET SDK to build the project
        FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
        WORKDIR /src
        COPY . .
        RUN dotnet restore "GithubActionsDemo.csproj"
        RUN dotnet build "GithubActionsDemo.csproj" -c Release --no-restore
        RUN dotnet publish "GithubActionsDemo.csproj" -c Release -o /app/publish
        
        # Use the ASP.NET runtime to run the app
        FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
        WORKDIR /app
        COPY --from=build /app/publish .
        ENTRYPOINT ["dotnet", "GithubActionsDemo.dll"]
        EOF

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PW }}
      run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USER }}" --password-stdin

    - name: Build Docker image from generated Dockerfile
      run: docker build -t zekath/mydotnetapp:latest .

    - name: Push Docker image to Docker Hub
      run: docker push zekath/mydotnetapp:latest
